# Generated by Django 3.0.6 on 2020-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий')),
                ('coordinates', models.FloatField(verbose_name='Координаты')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
