# Generated by Django 3.0.6 on 2020-12-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='date',
        ),
    ]
