# Generated by Django 3.0.6 on 2020-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_places_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='username',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
