# Generated by Django 3.0.6 on 2020-12-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='coordinates',
        ),
    ]
