# Generated by Django 3.0.6 on 2020-12-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_places_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='username',
        ),
    ]
