# Generated by Django 3.0.6 on 2020-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_places_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='t_lat',
            field=models.FloatField(default=0, verbose_name='Первая координата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='t_lon',
            field=models.FloatField(default=0, verbose_name='Вторая координата'),
            preserve_default=False,
        ),
    ]
