# Generated by Django 3.0.6 on 2020-12-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20201222_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='username',
            field=models.CharField(default=0, max_length=50, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
    ]
